spring: 
  profiles: 
    active: 
    - dev

---
server: 
  port: 8001

spring: 
  profiles: dev
  application:
    name: springcloud-dept-dev  #微服务的名字

---
server: 
  port: 8001

spring: 
  profiles: test
  application:
    name: springcloud-dept-test  #微服务的名字