spring: 
  profiles: 
    active: 
    - dev

--- 
server: 
  port: 8211
spring: 
  profiles: dev #开发环境
  application: 
    name: springcloud-demo-config-client-dev-1
eureka: 
  client: #客户端注册进入eureka服务列表内
    service-url: 
      defaultZone: http://eureka7001.com:7001/eureka
      #集群配置，注册进3个eureka服务里面

--- 
server: 
  port: 8212
spring: 
  profiles: test #开发环境
  application: 
    name: springcloud-demo-config-client-test
eureka: 
  client: #客户端注册进入eureka服务列表内
    service-url: 
      defaultZone: http://eureka7001.com:7001/eureka
      #集群配置，注册进3个eureka服务里面

# 需保存为utf-8格式